config/routes.rb
NannyApp::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"
  get "home/contact"
  get "home/info"
  get "home/about"

  get "home/switch_location"

  # get "captcha", :to => "home#captcha"

  # resources :products
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }

  resources :users,:except => [:show]
  resources :references
  resources :users do
    resources :user_roles
  end

  resource :profile do
    get :upload_photo
    put :save_photo
    #get :crop
  end
  
  match 'dashboard' => 'home#general', :as => 'user_root'
  match 'general' => 'home#general', :as => 'user_root'

  resources :education_and_interests do
    collection do
      get 'language_lists', :to => "education_and_interests#language_lists"
    end
  end


  get   "/contact", :to => "home#contact"
  post  "/contact", :to => "home#send_email"

end

app/controllers/education_and_interests_controller.rb
class EducationAndInterestsController < ApplicationController
  
  before_filter :prepare_user

  def index
    prepare_build_relation
  end

  def create
    success = @user.update_attributes(params[:user])
    if success
      validate_language_and_availability
      flash[:success] = "Education and Interesets saved"
    else
      flash[:error] = @user.errors.full_messages
    end
    redirect_to :action => :index
  end

  def language_lists
    keywords  = params[:term].split(",")
    keyword   = keywords.last.strip
    result    = []
    Language::LIST_OF_LANGUAGE.each do |l| 
      result << {:label => l[0], :value => l[1]} if !already_present_in(keywords, l[0])
    end
    render :json => result.compact
  end

  private

  def validate_language_and_availability
    validate_availability_params(params[:user][:availabilities_attributes])
    validate_language_params(params[:user][:languages_attributes])
  end
 
  def validate_availability_params(params)
    new_avails = params.map{|h| combine_hour_params(h[1])}
    current_avails = @user.availabilities.map{|a| {:id => a.id, :hour => "#{a.start_hour}#{a.end_hour}#{a.day_of_week}"}}    
    current_avails.each do |a|
      Availability.find(a[:id]).delete if !new_avails.include?(a[:hour])
    end
  end

  def validate_language_params(params)
    new_lang = params.map{|l| l[1][:language]}
    current_lang = @user.languages.map{|l| {:id => l.id, :lang => l.language}}
    current_lang.each do |l|
      Language.find(l[:id]).delete if !new_lang.include?(l[:lang])
    end
  end

  def combine_hour_params(p)
    arr = p.map{|a| a[1] if a[0] != "id"}.compact
    arr.join()
  end

  def prepare_user
    @user = current_user
  end
  
  def prepare_build_relation
    @user.availabilities.build   if @user.availabilities.blank?
    @user.build_education   if @user.education.blank?    
    @user.languages.build   if @user.languages.blank?
    @user.build_user_detail if @user.user_detail.blank?
  end

  def already_present_in(array, value)
    array.map{|k| k.strip}.include?(value)
  end
end

app/views/education_and_interests/_form_availability.html.erb
<div id="availibilty-selector">
  <%- worktimes = [[1, "6am - 10am"], [2, "10am - 2pm"], [3, "2pm - 6pm"], [4, "6pm - 10pm"], [5, "10pm - 2am"], [6, "Overnight"]] %>
  <%- days = [[1, "S"], [2, "M"], [3, "T"], [4, "W"], [5, "T"], [6, "F"],[7, "S"]]%>
  <table id="availibilty">
    <thead>
      <tr>
        <td></td>
        <%- days.each do |d| %>
          <td><%= d[1] %></td>
        <% end %>
      </tr>
    </thead>

    <tbody>
      
      <%- worktimes.each do |wt| %>
        <tr>
          <td class="label <%= wt[0]%>"><%= wt[1] %></td>
            <%- days.each do |d| %>
              <td class="<%= "worktimes_#{wt[0]} days_#{d[0]} #{selected_availibility_time(wt[1],d[0])}"%>"></td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="hidden">
    <%= f.fields_for :availabilities do |f| %> 
      <%- class_name = "#{f.object.start_hour}#{f.object.end_hour}#{f.object.day_of_week}"%>
      <%= f.hidden_field :id, :class => class_name %>
      <%= f.hidden_field :start_hour, :class => class_name %>
      <%= f.hidden_field :end_hour, :class => class_name %>
      <%= f.hidden_field :day_of_week, :class => class_name %>  

    <% end %>
  </div>
</div>

app/views/education_and_interests/_form_education.html.erb
<%= f.select :level, options_for_select(Education::LEVEL) %>
<%= f.text_field :school_name, :placeholder => "School name" %>
<%= f.select :degree, options_for_select(Education::LEVEL) %>
<%= f.text_field :major, :placeholder => "Major" %>
<%= f.text_field :graduation_year, :placeholder => "Graduation year" %>

app/views/education_and_interests/_form_language.html.erb
<div id="language-lists">
  
    <%- @user.languages.each do |l| %>
      <% if l.persisted? %>
        <div class="title">
          <span class="label"><%= l.language %></span>
          <span class="remove">&times;</span>
        </div>
      <%- end %>
    <%- end %>

  <div class="field">
    <%= f.fields_for :languages do |fl|%>
      <%- class_name = fl.object.persisted? ? fl.object.language.gsub(" ", "_").downcase : ""%>
      <%= fl.hidden_field :id, :class => class_name %>
      <%= fl.hidden_field :language, :class => class_name %>
    <%- end -%>
  </div>
</div>
<br clear="all"/>
<div id="language-add">
  <%= select_tag 'languages', options_for_select(Language::LIST_OF_LANGUAGE) %>
  <span class="btn add">add</span>
</div>

app/views/education_and_interests/_form_user_detail_1.html.erb
<ul id="user-detail-1">
  <li>
    <%= f.check_box :live_in %>
    <%= f.label :live_in, "I'm interested in working as a live-in" %>
  </li>

  <li>
    <%= f.check_box :summer %>
    <%= f.label :summer, "I'm available during summer" %>
  </li>

  <li>
    <%= check_box_tag 'respond_by',"",  :checked => @user.user_detail.present? ? "checked" : "" %>
    <%= f.label :respond_by, "I'm committed to respond messages from families seeking care wihtin:" %>
    <%= f.select :respond_by, options_for_select([1,2,3,4,5,6,7]) %>
    <%= label_tag "days" %>
  </li>
</ul>

app/views/education_and_interests/_form_user_detail_2.html.erb
<ul id="user-detail-1">
  <li>
    <%= f.check_box :run_errands %>
    <%= f.label :run_errands, "Errands" %>
  </li>

  <li>
    <%= f.check_box :get_groceries %>
    <%= f.label :get_groceries, "Grocery Shopping" %>
  </li>

  <li>
    <%= f.check_box :do_light_house_keeping %>
    <%= f.label :do_light_house_keeping, "Light housekeeping" %>
  </li>

  <li>
    <%= f.check_box :do_laundry %>
    <%= f.label :do_laundry, "Laundry" %>
  </li>
</ul>

app/views/education_and_interests/index.html.erb
<div id="preferences_container" class="left">
  
  <div class="top">
    <div class="pref_header">Education and Availability</div>
    <div class="text">The more information you provide the easier it will be for us to match you with the perfect job within a caring home</div>
    </div>
    <%= form_for @user, :url => education_and_interests_path, :html => {:method => :post} do |f| %>
      <div id="preferences_left" class="left">
        
        <!-- Education Form goes here -->
        <h3>Education</h3>
        <%= f.fields_for :education do |fe| %>
          <%= render :partial => 'form_education', :locals => {:f => fe}%>
        <% end %> 
        <br/>
        <br/>

        <!-- Language Form goes here -->
        <h3>Language</h3>
        <%= render :partial => 'form_language', :locals => {:f => f}%>
      
      </div>
      <div id="preferences_left" class="left">
        <!-- Availability Form goes here -->
        <h3>Availability</h3>        
          <%= render :partial => 'form_availability', :locals => {:f => f}%>
        <br/>
        <br/>
        <!-- Additional Services Form goes here -->
        <h3>Highlight above all the time slots that you are available to work</h3>
        <%= f.fields_for :user_detail do |fud| %>          
          <%= render :partial => 'form_user_detail_1', :locals => {:f => fud}%>
        <% end %>
      </div>
      <div id="preferences_left" class="left">
        <!-- Hobbies and interest Form goes here -->
        <h3>Hobbies and Interest</h3>
          <%= f.text_area :interests, :placehoder => "Hobbies and interests" %>
        <br/>
        <br/>
        <!-- Additional Services Form goes here -->
        <h3>Additional Services</h3>
        <%= f.fields_for :user_detail do |fud| %>          
          <%= render :partial => 'form_user_detail_2', :locals => {:f => fud}%>
        <% end %>

        <%= f.submit "Submit"%>
      </div>
    <% end %>
 </div>
 <div class="clear"></div>
</div>

<div class="clear"></div>


<script type="text/javascript">
  $(document).ready(function(){
    initAvailibiltyTable();
    addLanguage()
  })
</script>