config/routes.rb
NannyApp::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"
  get "home/contact"
  get "home/info"
  get "home/about"

  get "home/switch_location"

  # get "captcha", :to => "home#captcha"

  # resources :products
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }

  resources :users,:except => [:show]
  resources :references
  resources :users do
    resources :user_roles
  end

  resource :profile do
    get :upload_photo
    put :save_photo
    #get :crop
  end
  
  match 'dashboard' => 'home#general', :as => 'user_root'
  match 'general' => 'home#general', :as => 'user_root'

  resources :education_and_interests do
    collection do
      get 'language_lists', :to => "education_and_interests#language_lists"
    end
  end


  get   "/contact", :to => "home#contact"
  post  "/contact", :to => "home#send_email"

end

app/views/shared/_captcha.html.erb
<div id="captcha">
  <h2>Please Verify that you are human using</h2>
  <%= recaptcha_tags(:public_key => '6LdsmNgSAAAAAAn88eGVDmPSlWmcs_vq2LNeZPTx') %>
  or
<div class="QapTcha"></div>
<%= submit_tag "register", :class => "submit_register" %>
</div>

app/views/shared/_footer.html.erb
 <footer>
    <div class="left">Royal Nanny Care &copy; 2012 - Privacy Policy and Terms & Conditions </div>
    <div class="right" id="footer_links">
    	<%=link_to 'About Us',:home_about %> | <%=link_to 'Pre-Launch Info',:home_info %> | <%=link_to 'Contact Info',:home_contact%>
  
    </div>
    <div class="clear"></div>
 </footer>

app/views/shared/_login_links.html.erb
<!--
<%if !user_signed_in?%>
  <%= link_to "Sign in", new_session_path(:user) %>
<%else%>
  <%= link_to "Sign Out", destroy_user_session_path %>
<%end%>
-->

app/views/shared/_progress_bar.html.erb
 <div id="status_box">
      

        <div id="status_bar"><div id="status_progress" style="width:<%=@percent_complete%>%"></div> </div>
        <ul><li>0%</li><li>25%</li><li>50%</li><li>75%</li><li style="margin-right:0px;">100%</li></ul>

      </div>  

app/views/shared/_signup.html.erb
<%= form_for(:user, :url => user_registration_url, :html => { :id => "ajax_signup",:autocomplete=>"off"}, :remote => false) do |f| %>
<div><%= f.text_field :full_name, :placeholder => "Full Name",:class=>"sign_up_field",:title=>"Full Name" %></div>
  <div><%= f.email_field :email, :placeholder => "Email",:class=>"sign_up_field",:title=>"Email Address"   %></div>
  <div><%= f.password_field :password,:value=>'', :placeholder => "Password",:class=>"sign_up_field password_field",:title=>"Password",:onClick=>"changeToPassword(this)"   %></div>
  <div><%= f.password_field :password_confirmation,:value=>'' ,:placeholder => "Password Confirmation",:class=>"sign_up_field password_field",:title=>"Password Confirmation",:onClick=>"changeToPassword(this)"   %></div>
  <div><%= f.hidden_field :zip_code,:value=>@zip%></div>
  <div class ="roles">
  
			
			<label for="Provider_1"><%= f.radio_button :role, '1', { :checked => true ? true : false  } %>Provider</label><br/>
			<label for="Care_Seeker_2"><%= f.radio_button :role, '2', { :checked => false ? true : false  } %>Care Seeker</label>

  
  </div>
  <div class="group-submit">
    <%= image_submit_tag "sign_up.jpg", :rel => "facebox", :class => "signup" %> 
  </div>  <% end %>
  

  