config/routes.rb
NannyApp::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"
  get "home/contact"
  get "home/info"
  get "home/about"

  get "home/switch_location"

  # get "captcha", :to => "home#captcha"

  # resources :products
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }

  resources :users,:except => [:show]
  resources :references
  resources :users do
    resources :user_roles
  end

  resource :profile do
    get :upload_photo
    put :save_photo
    #get :crop
  end
  
  match 'dashboard' => 'home#general', :as => 'user_root'
  match 'general' => 'home#general', :as => 'user_root'

  resources :education_and_interests do
    collection do
      get 'language_lists', :to => "education_and_interests#language_lists"
    end
  end


  get   "/contact", :to => "home#contact"
  post  "/contact", :to => "home#send_email"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, :only=>[:general_info]#:except => [:contact,:index,:location,:captcha,:switch_location] 
  before_filter :preferences, :only => [:index,:general]
  before_filter :unsigned_user, :only=>[:index]


  def index
    location = user_location(nil)
    
   
    @addr = ""
    @zip = ""

    if location
    loc_info = location[0].try(:data)
    logger.debug(loc_info)
    unless loc_info.nil?
      @addr = "#{loc_info['city']}, #{loc_info['region_code']}" 
      @zip = loc_info['zip_code']
    end
    
    end
     if !user_signed_in? || true
     render :layout=>'login'
   
    else
      render 'dashboard'       
    end 
  end

  def general_info
    @is_confirmed = current_user.confirmed?
    @has_photo = current_user.photo_file_name.present?
    @has_prefs = !current_user.preference.nil?
    @has_fb = current_user.uid.present?
    @percent_complete = 0;
    @percent_complete +=25 if @is_confirmed
    @percent_complete +=25 if @has_photo
    @percent_complete +=25 if @has_prefs 
    @percent_complete +=25 if @has_fb 
  end
  
  def about;end

  def info;end

  def contact;end

  def send_email
    
    if params[:email].blank?
        flash[:notice] = "Please enter a valid email address"
        redirect_to contact_path
    else
     
     puts "************************************"
     puts params
     puts "*************************************"
    
     NotificationMailer.contact_us(params[:name], params[:email], params[:subject], params[:body]).deliver
     flash[:notice] = "You're email has been sent"
    redirect_to contact_path
    end
  end
  
  def captcha
    render layout=> false
  end
  
  def switch_location
    zip = params["zip_code"]
     puts zip
     puts params
    unless zip.nil?
      puts zip
      arr = Geocoder.search(zip)
      data = arr[0].data
      #[#<Geocoder::Result::Google:0x4cf4e08 @data={"address_components"=>[{"long_name"=>"27705", "short_name"=>"27705", "types"=>["postal_code"]}, {"long_name"=>"Durham", "short_name"=>"Durham", "types"=>["locality", "political"]}, {"long_name"=>"North Carolina", "short_name"=>"NC", "types"=>["administrative_area_level_1", "political"]}, {"long_name"=>"United States", "short_name"=>"US", "types"=>["country", "political"]}], "formatted_address"=>"Durham, NC 27705, USA", "geometry"=>{"bounds"=>{"northeast"=>{"lat"=>36.1059459, "lng"=>-78.90533789999999}, "southwest"=>{"lat"=>35.952911, "lng"=>-79.04770599999999}}, "location"=>{"lat"=>36.025609, "lng"=>-78.9853813}, "location_type"=>"APPROXIMATE", "viewport"=>{"northeast"=>{"lat"=>36.1059459, "lng"=>-78.90533789999999}, "southwest"=>{"lat"=>35.952911, "lng"=>-79.04770599999999}}}, "types"=>["postal_code"]}, @cache_hit=nil>]
      zip = data["address_components"][0]["long_name"]
      addr = data["formatted_address"]     
      addr = addr.sub(/\d+.*$/,"")
      res = {:zip=>zip,:address=>addr}
      logger.debug data
      render :json=>res.to_json
    else
      render :json=>"fail".to_json ,:status => :failure
    end  
  end


  protected

  def preferences
    @user_preference = current_user.preference.present? ? current_user.preference :  current_user.build_preference if user_signed_in?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="sub_container">
<div class="interior_page_title">About Us</div>
<p>
	Welcome to Royal Nanny Care; the premier on-line
	registry where families meet exceptional, candidates
	for their childcare and household needs.
	
</p>	
<p>
	Nancy Poulous Boehm, President of RoyalNannyCare.com; has been
	creating quality child care options for families for over 25 years.
	
</p>	

<p>
	Nancy; an educator, mother and developer of private Montessori Schools
	through-out the country; clearly understands the value of exceptional child care
	and work-life balance.
	
</p>	

<p>
	The goal of RoyalNannyCare.com is to create a place
	for families to find educated,experienced candidates;
	focusing on the specific needs of the family.
	
</p>	

<p>We wish you success in your search;don't hesitate to contact us if you need assitance</p>	

  <hr/>
</div>

app/views/home/captcha.html.erb
<%= render :partial => "shared/captcha"%>

app/views/home/contact.html.erb
 <div class="sub_container" id="contact_sub_container"> 	
 	
  <div class="contact_us">
  	 <% if flash[:notice] %>
      <div class="notice" style="text-align:center;width:224px;font-weight:bold;"><%= flash[:notice] %></div>
    <% end %>
  	 <%= form_tag contact_path do %>
    <fieldset class="fields">
      <div class="field">
        <%= label_tag :name %>
        <%= text_field_tag :name %>
      </div>
      
      <div class="field">
        <%= label_tag :email %>
        <%= text_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :subject %>
        <%= text_field_tag :subject %>
      </div>
      
      <div class="field">
        <%= label_tag :body %>
        <%= text_area_tag :body %>
      </div>
    </fieldset>
     <div id="contact_submit" style="float:right">
      <%= submit_tag "Send" %>
    </div>
    
      <% end %>
    </div>
   
   <div class="contact_text left" >
   
      <div class="interior_page_title">Contact Information</div>
      
		<div>Contact us for media information and business opportunities.
		We are currently in the process of building our business and
		are actively seeking companies to provide us of a wide
		spectrum of services ranging from background checks, to
		special training and certifications</div>
		
      	<div class="small" style="margin-top:10px;">Companies we are looking for</div>
      	
      	<div class="big">Background Check Companies</div>
      	<div>We are looking for several companies to create a liason with in order to run
           the background checks of our users in our website.</div>
           
        <div class="big">News & Media</div>
        <div>Our goal is to create ing an impact from the start. We are open to chat online
           publications and other media services to provide a hint of what we are about
           to do with Royal Nanny Care.</div>   
     
        <div class="big">Special Training and Certifications</div>
<div>We are aiming to create a listing of companies that provide special training
and certfication for care providers, such as CPR, Nutrition, Elder Care, etc.</div>
    
    </div>

</div>

app/views/home/dashboard.html.erb
<div id="preferences_container" class="left">
  
  <div class="top">
    <div class="pref_header">Move to the front of the line</div>
    <div class="text">Our registry will soon be filled with high quality care jobs and
      you will be among the first to land them</div>
    </div>

    <div id="preferences_left" class="left">
      <p>* Required Fields</p>
      <% if @user_preference.present? %>
        <%= form_for current_user, :html => {:class => "edit_preferences" }, :validate => true do |f| %>
          <%= f.text_field :street_address, :title => "Street Address*", :class => "info-input" %>
          <%= text_field_tag "stree_address2", '', :size => 30, :class => "info-input" %>
          <%= f.text_field :city, :title => "City*", :class => "info-input" %>
          <%= f.text_field :state, :title => "State*", :class => "info-input" %>
          <%= f.text_field :zip_code, :title => "Zip Code*", :class => "info-input" %>
          <%= f.text_field :phone_number, :title => "Phone*", :class => "info-input" %>
          <div id="show-phone-container">
            <label for="user_show_phone">
              <%= f.check_box :show_phone %>
              Show this number in my profile
            </label>
          </div>
          <div id="date_of_birth_holder">
            <%= label_tag 'date_of_birth', 'Birthday:* (must be 18+)' %>
            <%= f.date_select :date_of_birth, :prompt => {:year => 'Year', :month => 'Month', :day => 'Day', }, :start_year => 1950, :order => [:month, :day, :year] %>
          </div>
          <%= f.text_field :religion, :title => "Religion", :class => "info-input"%>
    </div>
    <div id="preferences_left" class="left">
      <h1>Preferences!</h1>
          <%= f.fields_for :preference do |fp| %>
            <% @user_preference.attributes.map{|p| p}[1..12].each do |attr| %>
              <% value = (attr[1].nil? ? false : attr[1]) %>
              <%= fp.hidden_field attr[0].to_sym, :value => value %>
            <% end %>      
        <% end %>
      
      <%= display_user_preferences_table(@user_preference) %>

      <h2>Tap or click on each preference</h2>
      <p class="preference_question"><%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'military_spouse')",:class=>"fade_#{!@user_preference.military_spouse}"  %>
       I'm a military spouse
     </p>
     <p class="preference_question">
       <%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'speaks_english')",:class=>"fade_#{!@user_preference.speaks_english}"  %>
       I speak fluent english</p>
       <p class="preference_question">
        <%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'eligible_to_work')",:class=>"fade_#{!@user_preference.eligible_to_work}"  %>
        I'm eligible to work in the US</p>
      
      <div class="layout-slider">
        <%= text_field_tag :miles_slider, @user_preference.miles_to_travel || 0 %>
        <p id="miles_count">0 Miles</p>
      </div>
      <% end %>
      <% end %>
      
      <%= submit_tag "Save preferences", :id => "save_preferences" %>
      </div>

      <div id="preferences_right" class="left">
       <div id="status_box">
        <%=image_tag('status_bars.png')%>

        <div id="status_bar"><div id="status_progress" style="width:<%=@percent_complete%>%"></div> </div>
        <ul><li>0%</li><li>25%</li><li>50%</li><li>75%</li><li style="margin-right:0px;">100%</li></ul>

      </div>  

    

      <div id="summary_header">Summary </div> 
      <ul class="status_list">
       <%=display_user_preferences(@user_preference) unless @user_preference.nil? %>
       <li>You are willing to travel 0 miles.</li>
       <li>You have not connected your</li>
     </ul>
    
   </div> 
 </div>
 <div class="clear"></div>
</div>

<div class="clear"></div>

app/views/home/general.html.erb
<% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'login_out') %>
<% else %>
    <%= link_to('Login', new_user_session_path, :class => 'login_out')  %> 
<% end %>
<div id="preferences_container" class="left">
  <div class="top">
    <div class="pref_header">Move to the front of the line</div>
    <div class="text">Our registry will soon be filled with high quality care jobs and
      you will be among the first to land them</div>
    </div>
    
     <%= link_to "Manage your References", new_reference_path, :id=>'create_reference_dialog', :class => 'login_out' %>
    <div id="preferences_left" class="left">
      <p>* Required Fields</p>
      <% if @user_preference.present? %>
        <%= form_for current_user, :html => {:class => "edit_preferences" }, :validate => true do |f| %>
          <%= f.text_field :street_address, :title => "Street Address*", :class => "info-input" %>
          <%= text_field_tag "stree_address2", '', :size => 30, :class => "info-input" %>
          <%= f.text_field :city, :title => "City*", :class => "info-input" %>
          <%= f.text_field :state, :title => "State*", :class => "info-input" %>
          <%= f.text_field :zip_code, :title => "Zip Code*", :class => "info-input" %>
          <%= f.text_field :phone_number, :title => "Phone*", :class => "info-input" %>
          <div id="show-phone-container">
            <label for="user_show_phone">
              <%= f.check_box :show_phone %>
              Show this number in my profile
            </label>
          </div>
          <div id="date_of_birth_holder">
            <%= label_tag 'date_of_birth', 'Birthday:* (must be 18+)' %>
            <%= f.date_select :date_of_birth, :prompt => {:year => 'Year', :month => 'Month', :day => 'Day', }, :start_year => 1950, :order => [:month, :day, :year] %>
          </div>
          <%= f.text_field :religion, :title => "Religion", :class => "info-input"%>
    </div>
    <div id="preferences_left" class="left">
      <h1>Preferences!</h1>
          <%= f.fields_for :preference do |fp| %>
            <% @user_preference.attributes.map{|p| p}[1..12].each do |attr| %>
              <% value = (attr[1].nil? ? false : attr[1]) %>
              <%= fp.hidden_field attr[0].to_sym, :value => value %>
            <% end %>      
        <% end %>
      
      <%= display_user_preferences_table(@user_preference) %>

      <h2>Tap or click on each preference</h2>
      <p class="preference_question"><%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'military_spouse')",:class=>"fade_#{!@user_preference.military_spouse}"  %>
       I'm a military spouse
     </p>
     <p class="preference_question">
       <%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'speaks_english')",:class=>"fade_#{!@user_preference.speaks_english}"  %>
       I speak fluent english</p>
       <p class="preference_question">
        <%= link_to image_tag('pref_button.png'), "javascript:void(0)", :onclick => "handleClick(this,'eligible_to_work')",:class=>"fade_#{!@user_preference.eligible_to_work}"  %>
        I'm eligible to work in the US</p>
      
      <div class="layout-slider">
        <%= text_field_tag :miles_slider, @user_preference.miles_to_travel || 0 %>
        <p id="miles_count">0 Miles</p>
      </div>
      <% end %>
      <% end %>
      <%= submit_tag "Save preferences", :id => "save_preferences" %>
      </div>

      <div id="preferences_right" class="left">
      <%=render :partial=>"shared/progress_bar"%>
    

      <div id="summary_header">Summary </div> 
      <ul class="status_list">
       <%=display_user_preferences(@user_preference) unless @user_preference.nil? %>
       <li>You are willing to travel 0 miles.</li>
       <li>You have not connected your</li>
     </ul>
   </div> 
 </div>
 <div class="clear"></div>
</div>

<div class="clear"></div>

app/views/home/index.html.erb
<div class="sub_container">

	<div id="signup_box" class="right">
         <%=raw flash[:error]%>
    <div id="signup_box_top" class="element">Register to participate in the pre-launch of Royal Nanny Care</div>
    <div id="signup_box_middle" class="element">Number of pre-registrations are limited, don't be left out.</div>
    <div id="signup_box_bottom" class="element">
		<div id="signup_fields" class="left">
			<%= render :partial => "shared/signup" %>
		</div>

		<div id="faceook_signup" class="left">
			<%= link_to image_tag('fb_login_button.png'), user_omniauth_authorize_path(:facebook)%>		
			 <ul>
			  <li>Higher Standard of Service</li>
	          <li>Great Families to work for</li>
	          <li>Higher Salary</li>
			</ul>		
		</div>
		<div class="clear"></div>
		<div id="location">
			<div id="location_box">
				Your location is
				<span id="location_text"> <%= @addr%> </span>
				<div class="popbox">
					<a class='open' href="javascript:void(0)" > Change Location </a>
					<div class='collapse'>
						<div class="box">
							<div class="close right">
								<a href="javascript:void(0)"> <%= image_tag('x.png')%></a>
							</div>
	                          <%= form_tag(home_switch_location_path , :id=>'loc_form', :method => :get,:remote => true,'data-target'=>'location',:condition => "validate_mail()") do %>
								<div class="box_text">
									Change Your Location
									<br/>						
									
								</div>

								<div class="done left">
									<%= image_submit_tag('done.png') %>
								</div>
							
							  <%end%>
						</div>
					</div>
				</div>
			</div>
		</div>
	
	 </div>
	
</div>

	<div class="clear"></div>
</div>


<div id="success_reg" style="display:none">
		<p>Thank you for participating in the pre-launch of ROYALNANNYCARE.com, we are elated to welcome you into the royal family.</p>
			<p> The official launch of ROYALNANNYCARE.com is almost upon us. As we continue building our application and online registry we 
			 would like to take this opportunity to invite you to partake in our social campaigns and join our efforts of spreading the 
			 good news about ROYALNANNYCARE.com. </p>
			<p>We believe in strong customer service and building upon our users experience. Which is why 
			 we are asking for your help. We are actively searching for individuals to help us spread the word so that we can help others. 
			 We value your opinion.</p>
			 <p>You should have an email awaiting you in your mailbox. Please confirm your pre-registration 
			 	and help us help others. Together we can care for theworld.</p></div>
	
	
</div>	

app/views/home/info.html.erb
<div class="sub_container">
<div class="interior_page_title">Pre-launch</div>



<p>
   Registering for our pre-launch has many benefits.
<p>
Sign up today if you are a CAREGIVER or TUTOR seeking a wonderful family to work for; where your talents, education and experience will be greatly appreciated.
</p>
<p>
* We support our Caregivers.... stay connected and look for our updates... providing great resources to offer as our affiliates grow!
<br/>
* Higher salaries than average; commensurate with experience, specific skills and training.
</p>

<h2>BE A PIONEER / TELL A FRIEND</h2>
<p>
Help us build our community and participate in our raffles of free background checks, royal coin credits, listing highlights and more.
</p>

</div>