config/routes.rb
NannyApp::Application.routes.draw do
  root :to => 'home#index'
  
  get "home/index"
  get "home/contact"
  get "home/info"
  get "home/about"

  get "home/switch_location"

  # get "captcha", :to => "home#captcha"

  # resources :products
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }

  resources :users,:except => [:show]
  resources :references
  resources :users do
    resources :user_roles
  end

  resource :profile do
    get :upload_photo
    put :save_photo
    #get :crop
  end
  
  match 'dashboard' => 'home#general', :as => 'user_root'
  match 'general' => 'home#general', :as => 'user_root'

  resources :education_and_interests do
    collection do
      get 'language_lists', :to => "education_and_interests#language_lists"
    end
  end


  get   "/contact", :to => "home#contact"
  post  "/contact", :to => "home#send_email"

end

app/models/reference.rb
class Reference < ActiveRecord::Base
	belongs_to :user
	has_many :reference_types, :dependent => :destroy

	def private_description
		if self.private == true 
			"published in profile"
		else
			"upon request only"
		end
	end

	def reference_types_text
		profiles = []

		if self.reference_types.blank? == false && self.reference_types.first.name == 'ga'
			'General References (All Services)'
		else
			self.reference_types.each do |r|
				profiles << ReferenceType::PROFILE_TYPES.map{ |k,v| v == r.name ? k : nil }.compact
			end
			profiles.map! { |r| r }.join(",")
		end
	end
end

app/models/reference_type.rb
class ReferenceType < ActiveRecord::Base
  belongs_to :reference

  PROFILE_TYPES = {'Baby Sitter' => 'bs', 'Nanny' => 'na', 'Governess' => 'go', 'Pet Sitter' => 'ps', 
  					 'HouseKeeper' => 'hk', 'Senior Care' => 'sc', 'Tutor' => 'tu' }

  RELATIONSHIPS = {'Friend' => 'fa', 'Co-Worker' => 'cw', 'Family' => 'fa' }
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

	def index	
	end

	def new
		@reference = Reference.new
		@references = current_user.references
	end

	def edit
		@reference = Reference.find(params[:id])
	end

	def update
		@reference = Reference.find(params[:id])
		@reference.reference_types.delete_all
		params[:reference_types].each do |name|
			rt = ReferenceType.new(:name => name)
			@reference.reference_types << rt
		end

		if @reference.update_attributes(params[:reference])
			@references = current_user.references
		end
	end

	def create
		@reference = Reference.new(params[:reference])
		
		if params[:reference_for] == 'General'
			rt = ReferenceType.new(:name => 'ga')
			@reference.reference_types << rt
		else
			params[:reference_types].each do |name|
				rt = ReferenceType.new(:name => name)
				@reference.reference_types << rt
			end
		end
		
		@reference.user_id = current_user.id

		if @reference.save
			@references = current_user.references
		end
	end

	def destroy
		@reference = Reference.find(params[:id])
		@reference.destroy
		@references = current_user.references
		
		respond_to do |format|
			format.html { render :action => "new" }
	        format.js
		end
	end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<div id="reference-form">
	<%= form_for @reference, :remote => true do |f| %>
		<div>
			<%= f.text_field :name, :title => "Reference Name", :class => "reference-field" %>
			<%= f.text_field :phone_number, :title => "Phone Number", :class => "reference-field" %>
			<%= f.text_field :email, :title => "Email", :class => "reference-field" %>
			<%= f.select :relationship, options_for_select(ReferenceType::RELATIONSHIPS.each {|y| y }, @reference.relationship), :include_blank => true%>
		</div>
		<div id="reference_type_container">
			<ul>
				<li>Use this reference as a:</li>
				<li class="reference_general">
					<label for="reference_for_General">
						<%= radio_button_tag :reference_for, 'General' %> General References (For all services)
					</label>
				</li>
				<li>
					<label for="reference_for_Profile">
						<%= radio_button_tag :reference_for, 'Profile' %> Specific for
					</label>
				</li>
				<li>
					<%= select_tag(:reference_types, options_for_select(ReferenceType::PROFILE_TYPES.each {|y| y }, @reference.reference_types.map { |r| r.name } ), { :multiple => true, :size => 7 }) %>
				</li>
			</ul>
		</div>
		<div class="clear"></div>
		<div id="privacy_container">
			<p>Reference Privacy Level</p>
			<label for="reference_private_1"><%= f.radio_button :private, '1', { :checked => ( @reference.private == true ? true : false ) } %> Publish this reference in my profile</label><br/>
			<label for="reference_private_0"><%= f.radio_button :private, '0', { :checked => ( @reference.private == false ? true : false ) } %> Keep this reference only available upon request</label>
		</div>
		<div class="actions">
			<%= submit_tag 'Save' %>
		</div>
	<% end %>
</div>

app/views/references/_references.html.erb
<div class="clear"></div>
<div>
	<table id="reference-list">
		<tbody>
			<tr>
				<th>Name</th>
				<th>Privacy</th>
				<th>Care services it applies to</th>
				<th>&nbsp;</th>
			</tr>
		</tbody>
		<% @references.each do |reference| %>
			<tr>
				<td><%= reference.name %></td>
				<td><%= reference.private_description %></td>
				<td><%= reference.reference_types_text %></td>
				<td>
					<%= link_to 'Edit', edit_reference_path(reference), :remote => true %> | 
					<%= link_to 'Delete', reference, :confirm => 'Are you sure?', :method => :delete, :remote => true %>
				</td>
			</tr>
		<% end %>
	</table>
</div>
<div class="clear"></div>
<div id="agreement-container">
	<ul>
		<li><input type="checkbox" id="agreement" name="agreement"></li>
		<li id="agreement-text"><label for="agreement">By Checking this box I acknowledge 
		that all the references information I provide is accurate and agree that the Royal Nanny Care website reserve the right to contact such references and verify them on behalf of its members.</label></li>
		<li id="close-btn"><input type="button" id="reference-close" name="done" value="Done"/></li>
	</ul>
</div>

app/views/references/create.js.erb
$('#reference-list').html('<%= escape_javascript(render( :partial => "references" )) %>');
$("#agreement-container").remove();
$('form').find("input[type=text], textarea, select, input[type=radio]").val("");
$('form').find("input[type=radio]").attr("checked", false);

app/views/references/destroy.js.erb
$('#reference-list').html('<%= escape_javascript(render( :partial => "references" )) %>');
$("#agreement-container").remove();
$('form').find("input[type=text], textarea, select, input[type=radio]").val("");
$('form').find("input[type=radio]").attr("checked", false);

app/views/references/edit.html.erb
<div id="content">
	<h2>Manage Your References</h2>
	<%= render 'form' %>
	<table id="reference-list">
		<thead>
			<th>Name</th>
			<th>Privacy</th>
			<th>Care services it applies to</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</thead>
		<%= render :partial => @reference %>
	</table>
</div>

app/views/references/edit.js.erb
$("#reference-form").html("<%= escape_javascript(render(:partial => "form"))%>");

app/views/references/new.html.erb
<div id="content">
	<h2>Manage Your References</h2>
	<%= render 'form' %>
	<%= render :partial => 'references' %>
</div>

app/views/references/update.js.erb
$('#reference-list').html('<%= escape_javascript(render( :partial => "references" )) %>');
$("#agreement-container").remove();
$('form').find("input[type=text], textarea, select, input[type=radio]").val("");
$('form').find("input[type=radio]").attr("checked", false);